# Generated by Django 5.0.6 on 2025-05-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('mileage', models.PositiveIntegerField(default=0)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('num_doors', models.PositiveIntegerField(default=4)),
                ('car_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('coupe', 'Coupe'), ('hatchback', 'Hatchback')], max_length=20)),
            ],
            options={
                'ordering': ['make', 'model'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('mileage', models.PositiveIntegerField(default=0)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('engine_cc', models.PositiveIntegerField()),
                ('has_sidecar', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['make', 'model'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('mileage', models.PositiveIntegerField(default=0)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('payload_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('axles', models.PositiveIntegerField(default=2)),
            ],
            options={
                'ordering': ['make', 'model'],
                'abstract': False,
            },
        ),
    ]
